platform :ios, '12.0'
inhibit_all_warnings!

target 'RxConveniencesExample' do
    pod 'CollectiveSwift', '~> 2.0'
    pod 'RxCocoa', '~> 5.0'
    pod 'RxRelay', '~> 5.0'
    pod 'RxSwift', '~> 5.0'
end
